FROM harbor.itc.inventec.net/infra/kong:latest
USER root

RUN luarocks install kong-plugin-response-transformer-tobase64
RUN luarocks install kong-plugin-file-log-exclusion
RUN luarocks install kong-plugin-concurrent-connection-quota
RUN chown -R kong:kong /usr/local/share/lua/5.1/kong/plugins/
USER kong

