_format_version: "2.1"
services:
  - name: ngi
    url: http://10.0.2.15:80 #specify upstream URL of service, as url implies protocol, no nned to write protocol
    routes:
      - name: nginx_route
        preserve_host: true
        methods:
          - GET
          - POST

    plugins:
      
      #- name: response-transformer
      #  config:
      #    remove:
      #      headers:
      #        - Server
      #    add:
      #      headers:
      #        - "X-Error-Message: error occur "
      #- name: file-log
      #  config:
      #    path: /var/log/kong/kong.log
      #- name: connection-limiting
      #  config:
      #    connections: 100
      #    reject_code: 503
      #- name: rate-limiting
      #  config:
      #    minute: 10
      #- name: ip-restriction
      #  config:
      #    deny:
      #      - 147.23.14.10      
