keepalived 配置举例：
global_defs {
  router_id LVS_DEVEL

 }
vrrp_script checkkong
{
    script "/healthcheck.sh"
    interval 5
    weight -20
}

vrrp_instance VI_1 {
   state MASTER
    interface enp0s3
   virtual_router_id 52
    priority 100
    advert_int 1

   authentication {
        auth_type PASS
        auth_pass 1111
    }
     unicast_peer {
        10.0.1.200
        10.0.1.201
    }
    virtual_ipaddress {
       10.0.1.231/24 dev enp0s3
    }
    #virtual_routes {
    #  10.190.40.0/23 via 10.191.4.1 src 10.191.7.4
    #}
    track_script
    {
        checkkong
    }
}


